version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: DjangoDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: GigaChadAdmin

  api:
    build:
      context: ./backend
      dockerfile: docker/docker_files/Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    